#include "batching/BatchingManager.hpp"
#include "batching/EdgeBatching.hpp"
#include "batching/HybridBatching.hpp"
#include "batching/VertexBatching.hpp"
#include "batching/SingleBatching.hpp"
#include "batching/DummyBatching.hpp"